"""Compile maintained agent instructions for offline handoff and native hosts."""
from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def body(relative: str) -> str:
    text = (ROOT / relative).read_text(encoding="utf-8").strip()
    if text.startswith("---\n"):
        text = text.split("---", 2)[2].strip()
    return text


def outputs() -> dict[str, str]:
    profiles = {}
    folder = ROOT / ".agents/skills/designer/references/profiles"
    for path in sorted(folder.glob("*.md")):
        relative = path.relative_to(ROOT).as_posix()
        text = body(relative)
        profiles[path.stem] = {
            "label": text.splitlines()[0].removeprefix("# "),
            "source": relative,
            "rules": [line[2:] for line in text.splitlines() if line.startswith("- ")],
        }
    data = {
        "designer": body(".agents/skills/designer/SKILL.md"),
        "workflow": body(".agents/HANDOFF-WORKFLOW.md"),
        "profiles": profiles,
    }
    encoded = json.dumps(data, ensure_ascii=False, indent=2)
    digest = hashlib.sha256(encoded.encode()).hexdigest()
    result = {
        "src/agent-resources.js": "// Generated by scripts/build-agent-resources.py; SHA256: " + digest
        + "\nwindow.VASAgentResources = Object.freeze(" + encoded + ");\n",
        ".agents/agent-resources.json": encoded + "\n",
    }
    for role in ("implementer", "designer", "reviewer"):
        source = f".agents/skills/{role}/SKILL.md"
        raw = (ROOT / source).read_text(encoding="utf-8")
        description = next(line[13:] for line in raw.splitlines() if line.startswith("description: "))
        instructions = "Read AGENTS.md and .agents/CONTEXT.md first.\n\n" + body(source)
        name = "vas_" + role
        toml = f'name = "{name}"\ndescription = {json.dumps(description, ensure_ascii=False)}\n'
        if role == "reviewer":
            toml += 'sandbox_mode = "read-only"\n'
        toml += "developer_instructions = " + json.dumps(instructions, ensure_ascii=False) + "\n"
        result[f".codex/agents/{name}.toml"] = toml
        # Omitted tool/model fields inherit the host's actual capabilities and permissions.
        result[f".claude/agents/{name}.md"] = (
            f"---\nname: vas-{role}\ndescription: {json.dumps(description, ensure_ascii=False)}\n"
            + ("tools: Read, Grep, Glob, WebFetch, WebSearch\n" if role == "reviewer" else "")
            + f"---\n\n{instructions}\n"
        )
    return result


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    stale = []
    for relative, content in outputs().items():
        path = ROOT / relative
        if args.check:
            if not path.is_file() or path.read_text(encoding="utf-8") != content:
                stale.append(relative)
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8", newline="\n")
    if stale:
        print("Agent resources are stale: " + ", ".join(stale))
        return 1
    print("Agent resources " + ("verified" if args.check else "built"))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
